export const stylisticRules = {
	'@stylistic/array-bracket-newline': 'off',
	'@stylistic/array-bracket-spacing': 'off',
	'@stylistic/array-element-newline': 'off',
	'@stylistic/arrow-parens': ['error', 'always'],
	'@stylistic/arrow-spacing': 'off',
	'@stylistic/block-spacing': 'off',
	'@stylistic/brace-style': 'off',
	'@stylistic/comma-dangle': 'off',
	'@stylistic/comma-spacing': ['error', { before: false, after: true }],
	'@stylistic/comma-style': 'off',
	'@stylistic/computed-property-spacing': 'off',
	'@stylistic/dot-location': 'off',
	'@stylistic/eol-last': 'error',
	'@stylistic/function-call-argument-newline': 'off',
	'@stylistic/function-call-spacing': 'off',
	'@stylistic/function-paren-newline': 'off',
	'@stylistic/generator-star-spacing': 'off',
	'@stylistic/implicit-arrow-linebreak': 'off',
	'@stylistic/indent': 'off',
	'@stylistic/jsx-quotes': 'off',
	'@stylistic/key-spacing': 'off',
	'@stylistic/keyword-spacing': 'off',
	'@stylistic/line-comment-position': 'off',
	'@stylistic/linebreak-style': 'off',
	'@stylistic/max-statements-per-line': 'off',
	'@stylistic/member-delimiter-style': 'error',
	'@stylistic/multiline-comment-style': 'off',
	'@stylistic/multiline-ternary': 'off',
	'@stylistic/new-parens': 'error',
	'@stylistic/newline-per-chained-call': 'off',
	'@stylistic/no-confusing-arrow': 'off',
	'@stylistic/no-extra-parens': 'off',
	'@stylistic/no-extra-semi': 'off',
	'@stylistic/no-floating-decimal': 'off',
	'@stylistic/no-mixed-operators': 'off',
	'@stylistic/no-mixed-spaces-and-tabs': 'off',
	'@stylistic/no-multi-spaces': 'off',
	'@stylistic/no-multiple-empty-lines': 'error',
	'@stylistic/no-tabs': 'off',
	'@stylistic/no-trailing-spaces': 'error',
	'@stylistic/no-whitespace-before-property': 'off',
	'@stylistic/nonblock-statement-body-position': 'off',
	'@stylistic/object-curly-newline': 'off',
	'@stylistic/object-curly-spacing': ['error', 'always'],
	'@stylistic/object-property-newline': 'off',
	'@stylistic/one-var-declaration-per-line': 'off',
	'@stylistic/operator-linebreak': 'off',
	'@stylistic/padded-blocks': 'off',
	'@stylistic/quote-props': ['error', 'as-needed'],
	'@stylistic/quotes': 'off',
	'@stylistic/rest-spread-spacing': 'error',
	'@stylistic/semi-spacing': 'off',
	'@stylistic/semi-style': 'off',
	'@stylistic/semi': 'off',
	'@stylistic/space-before-blocks': 'error',
	'@stylistic/space-in-parens': 'off',
	'@stylistic/space-infix-ops': 'error',
	'@stylistic/space-unary-ops': 'off',
	'@stylistic/spaced-comment': ['error', 'always', { exceptions: ['*'] }],
	'@stylistic/switch-colon-spacing': 'off',
	'@stylistic/template-curly-spacing': 'off',
	'@stylistic/template-tag-spacing': 'off',
	'@stylistic/type-annotation-spacing': 'error',
	'@stylistic/wrap-iife': 'off',
	'@stylistic/wrap-regex': 'off',
	'@stylistic/yield-star-spacing': 'off',
	'@stylistic/space-before-function-paren': [
		'error',
		{
			named: 'never',
			anonymous: 'ignore',
			asyncArrow: 'always',
		},
	],
	'@stylistic/padding-line-between-statements': [
		'error',
		{ blankLine: 'always', next: 'block', prev: '*' },
		{ blankLine: 'always', next: '*', prev: 'block' },
		{ blankLine: 'always', next: 'block-like', prev: '*' },
		{ blankLine: 'always', next: '*', prev: 'block-like' },
		{ blankLine: 'always', next: 'return', prev: '*' },
		{ blankLine: 'always', next: '*', prev: 'directive' },
		{ blankLine: 'always', next: ['interface', 'type'], prev: '*' },
		{ blankLine: 'always', next: '*', prev: ['const', 'let', 'var'] },
		{ blankLine: 'always', next: 'class', prev: '*' },
		{ blankLine: 'always', next: '*', prev: 'class' },
		{
			blankLine: 'any',
			next: ['const', 'let', 'var', 'export'],
			prev: ['const', 'let', 'var', 'export'],
		},
		{ blankLine: 'any', next: ['case', 'default'], prev: '*' },
		{ blankLine: 'any', next: '*', prev: ['case', 'default'] },
		{ blankLine: 'any', next: 'directive', prev: 'directive' },
	],
	'@stylistic/lines-between-class-members': [
		'error',
		'always',
		{ exceptAfterOverload: true, exceptAfterSingleLine: true },
	],
	'@stylistic/lines-around-comment': [
		'error',
		{
			afterBlockComment: false,
			afterLineComment: false,
			allowArrayEnd: true,
			allowArrayStart: true,
			allowBlockEnd: true,
			allowBlockStart: true,
			allowClassEnd: true,
			allowClassStart: true,
			allowObjectEnd: true,
			allowObjectStart: true,
			applyDefaultIgnorePatterns: true,
			beforeBlockComment: false,
			beforeLineComment: false,
		},
	],
	'@stylistic/max-len': [
		'error',
		{
			code: 120,
			ignoreTemplateLiterals: true,
			ignoreRegExpLiterals: true,
			ignoreStrings: true,
			ignoreComments: true,
		},
	],
};
